version: '3.9'

services:
  backend:
    build: ./backend
    container_name: media-server-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ${MEDIA_DIR_1:-./media}:/media
      - ./transcode:/transcode
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: media-server-ui
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped
